### ISSUE TITLE
Need a way to inject GitHub Private repo credentials from a Kubernetes Secret

### ISSUE THREAD

**Issue by hnougher** [bitnami/bitnami-docker-git#10]
### Name and Version

bitnami/git (and bitnami/node)

### What is the problem this feature will solve?

I have loaded NodeJS with bitnami/node Helm chart pulling the app from a private GitHub in Kubernetes.
But the only way I have worked out to get the credentials in is plaintext in the URL, which is not great for security.

And this package does not seem to have a way built in either.

There needs to be a way (properly documented) to use a Kubernetes Secret to pass the username/password when it is needed.

If a way already exists, it really needs to be added as a comment in the Helm chart as it took me hours to reach the plaintext method.

### What is the feature you are proposing to solve the problem?

Possibly use a "credential.helper" that pulls the environment variables?

https://alanedwardes.com/blog/posts/git-username-password-environment-variables/
https://git-scm.com/docs/gitcredentials#_custom_helpers

### What alternatives have you considered?

Would be even better if a DeployKey was possible.
But it is beyond me how that would be made into a Secret.

**Comment by hnougher** [comment]
Now after submitting this I see issue #2 ... though not sure how to easily construct said mountpoint without example.

I now suggest new sub-title in
https://github.com/bitnami/bitnami-docker-git#configuration
mentioning to use mountpoints and either an outline or link to how to do it in common cases.

I am thinking there might be a trend of following a web search of "bitnami/git" that end up here when people are learning like I am.

**Comment by alemorcuq** [comment]
Hi, @hnougher.

You can just mount your SSH key to the git container and set the `GIT_SSH_COMMAND` environment variable like this:

```
GIT_SSH_COMMAND='ssh -i private_key_file -o IdentitiesOnly=yes'
```

[Git documentation](https://git-scm.com/docs/git#Documentation/git.txt-codeGITSSHCOMMANDcode)
