### ISSUE TITLE
Simple git command results in error

### ISSUE THREAD

**Issue by DingieHub** [bitnami/bitnami-docker-git#3]
**Description**

I have entered the command to request git version, but resulted in an error.
Command:  docker run --name bitnami/git:latest --version

**Steps to reproduce the issue:**

1. [First Step]
Open powershell elevated to administrator
2. [Second Step]
Run the command

**Describe the results you received:**
unknown flag: --version
See 'docker run --help'.

**Describe the results you expected:**
git version 2.29.2.windows.2

**Additional information you deem important (e.g. issue happens only occasionally):**
I installed Docker Desktop with WSL 2 option

**Version**
latest

** Docker version **
Client: Docker Engine - Community
 Cloud integration: 1.0.1
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Windows Laptop: Lenovo Thnikpad i5 7th generation

**Comment by andresbono** [comment]
Hi @DingieHub, it seems the error is caused because of the parsing of the arguments of the `docker run` command. Note that the name for the container is missing. Try the following:

```
docker run --rm --name MY_CONTAINER_NAME bitnami/git:latest --version
```

- `--rm` Automatically remove the container when it exits.
- `--name string` Assign a name to the container.
