### ISSUE TITLE
Request for an Alpine based image

### ISSUE THREAD

**Issue by chirangaalwis** [bitnami/bitnami-docker-git#4]
**Description**
Why not $subject instead of a Debian based image?

**Comment by marcosbc** [comment]
Thanks for the suggestion! Our catalog is currently standarized on Debian 10 via minideb, except a few cases where `scratch` images make sense. This allows for consistency between all Bitnami solutions including Docker images, cloud images and others.

Alpine images offer some advantages like smaller image size, however, it is not enough for us to justify the required time investment for supporting them. Therefore we're unable to provide Alpine images.

**Comment by chirangaalwis** [comment]
@marcosbc Ack. Hence, closing the issue.
