### ISSUE TITLE
Modifying the standard php.ini file

### ISSUE THREAD

**Issue by richb201** [bitnami/bitnami-docker-git#5]
I hope I am asking this is the correct place? If not please let me know. My Dockerfile (and my docker-compose.yml) use bitnami/php-fpm. I am trying to set up remote debugging with xdebug on my EC2 server. It requires that I have "xdebug.remote_host=127.0.0.1"   But  when I run phpinfo on the server I see that it is set to  192.168.122.1. This will not work with xdebug.  I tried restting the following line in the Dockerfile and rebuilding it.

As you can see I am resetting php.ini in the Docker compose using this line. 
&& echo "xdebug.remote_host=127.0.0.1" >> /opt/bitnami/php/etc/php.ini 

But neither on my laptop (nor on my Ec2) can I find /opt/bitnami/php/etc/php.ini. Is my bitnami setup incorrectly?

[Dockerfile.txt](https://github.com/bitnami/bitnami-docker-git/files/7238344/Dockerfile.txt)

**Comment by carrodher** [comment]
This repo is for the bitnami/git container image, it seems you are using the bitnami/php-fpm one, can you create the issue at the [php-fpm repo](https://github.com/bitnami/bitnami-docker-php-fpm)? Thanks
