### ISSUE TITLE
can git lfs client be added to this image?

### ISSUE THREAD

**Issue by hectoralicea** [bitnami/bitnami-docker-git#6]
simple question.  can git lfs client be added to this image?  https://git-lfs.github.com/

that way we can support very large file systems

**Comment by javsalgar** [comment]
Thank you so much for the feature request! I will open a ticket for engineering so they can evaluate it. As it is not a critical feature, we cannot guarantee an ETA. If there are updates on the issue, we will update the ticket.

**Comment by candrews** [comment]
I look forward to hearing more about the progress made on this request. I'm really looking forward to having git lfs support in the `bitnami/git` image!

**Comment by carrodher** [comment]
Unfortunately, the task associated with this request is still on our backlog; for now, there are no plans to work on it in the short term.
As a workaround, you can build your own image based on this one adding git-lfs on top of it:
```Dockerfile
FROM bitnami/git

## Required commands to add git-lfs
```

**Comment by carrodher** [comment]
Hi, after checking internally, we decided to not add this extension by default into the image. You can still extend the image by creating a new one based on it
